const express = require('express')
const service = require('./service.js')
const router = express.Router()

// 统计访问量
router.put('/visit', service.countVisit)
// 登录
router.post('/login', service.login)
// 注册
router.post('/register', service.register)
// 获取个人信息
router.get('/user/:account', service.getInfo)
// 编辑个人信息
router.put('/user/:account', service.editInfo)
// 获取交流区帖子
router.get('/talk', service.getTalk)
// 获取指定类别的帖子
router.get('/talk/:classFlag', service.getTalkByClass)
// 修改指定帖子点赞状态
router.put('/talk/good/:account', service.changeGood)
// 获取指定用户点赞帖子
router.get('/talk/good/:account', service.getUserGood)
// 获取指定帖子评论
router.get('/talk/comments/:postID', service.getComments)
// 为指定帖子写评论
router.put('/talk/comments/:postID', service.setComments)
// 发布帖子
router.post('/talk/post', service.setPost)
// 获取七牛云uploadTaken
router.post('/token', service.getToken)
// 获取商品列表
router.get('/item?:params', service.getItem)
// 发布换物信息
router.post('/item', service.addItem)
// 新增个人物品
router.post('/myItem', service.addMyItem)
// 将物品加入收藏
router.put('/star/:account', service.addStar)
// 获取用户收藏夹
router.get('/star/:account', service.getStar)
// 物品点赞数加减
router.put('/star/likeCount/:uuid', service.changeLikeCount)
// 获取用户收藏夹详细列表
router.get('/starDetail/:account', service.getStarDetail)
// 获取用户地址
router.get('/user/address/:account', service.getAddress)
// 修改用户地址
router.put('/user/address/:account', service.changeAddress)
// 修改用户头像
router.put('/user/shortcut/:account', service.changeShortcut)
// 获取已发布物品
router.get('/item/myItem/:account', service.getMyOutItem)
// 下架已发布物品
router.delete('/item/myItem/:uuid', service.deleteOutItem)
// 获取个人物品
router.get('/myItem/:account', service.getMyItem)
// 下架个人物品
router.delete('/myItem/:uuid', service.deleteItem)
// 生成交换单
router.post('/item/exchange', service.postExchange)
// 获取交换单
router.get('/item/exchange?:params', service.getOrder)
// 取消申请交换
router.delete('/item/exchange/:uuid', service.cancelExchange)
// 确认交换
router.put('/item/exchange/:uuid', service.confirmExchange)
// 确认交换后去除掉换出物的其他申请表
router.delete('/item/exchange/other/:uuid', service.cleanOtherExchange)
// 修改我的物品交换状态
router.put('/myitem/:uuid', service.changeMyItemStatus)
// 修改物品交换状态
router.put('/item/status/:uuid', service.changeItemStatus)
// 确认收货
router.put('/order/confirm/:account', service.orderConfirm)
// 获取换出者微信号
router.get('/user/wechat/:account', service.getWechat)
// 获取租赁区物品
router.get('/rent/item?:params', service.getRentItem)
// 租赁物品
router.post('/rent/item', service.rentItem)

// -----------后台-------------
// 登录
router.post('/adminLogin', service.adminLogin)
// 获取用户列表
router.get('/user?:params', service.getUser)
// 删除用户
router.delete('/user/:account', service.deleteUser)
// 获取物品列表
router.get('/adminItem?:params', service.getItemAdmin)
// 获取订单列表
router.get('/order?:params', service.getOrderList)
// 删除订单
router.delete('/order/:uuid', service.deleteOrder)

module.exports = router